# Generated by Django 5.1.4 on 2025-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0002_rename_user_taskuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskUser',
            new_name='User',
        ),
    ]
